spring:
  application:
    name: OrderService
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/db
server:
  port: 8081
  address: 0.0.0.0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetch-registry: true

